In [119]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from scipy.stats import norm

In [120]:
# Get the mass vs. species data
data = pd.read_csv("train_data.csv")

In [121]:
# ----------------------------Generate testing data----------------------------
test_size = 100
# Get how many classes we need from the original data
output_dim = data.shape[0]
print("Num output classes: ", output_dim)

# Select a bunch of random rows in the data
np.random.seed(2)
masses = []
species = []
for i in range(test_size):
    rand_index = np.random.randint(output_dim)
    masses.append(data.at[rand_index, "Precise Mass"])
    # Use one-hot encodig of species strings to integers.
    species.append(rand_index)
masses = np.array(masses)

# TODO Accuracy goes down from 100% --> 0% as this uncertainty gets too small. Possibly use:
#      1) More accurate uncertainties?
#      2) A warning / default classification when vector becomes all 0s ([0,0,0,0,...0])?
# Generate noise for the same number of rows'. Multiply by an uncertainty factor representative of real data noise (e.g., usually around 10-100 ppm, or 1e-5 to 1e-4).
unc = 1e-4
noise = unc * np.random.standard_normal(size = test_size)

# Combine the noise and randomly selected masses to create our training data
x_data = masses + noise*masses
y_data = species
# print("x_data: ", x_data)
# print("y_data: ", y_data)

Num output classes:  97


In [122]:
# Make the known species masses into a row, then repeat for the length of the training data to prepare for mass array operations
# in the next cell
precise_masses = np.reshape(np.array(data["Precise Mass"]), (1,-1))
precise_masses = precise_masses.repeat(test_size,0)
print(precise_masses)

[[ 1.0084  2.0147 12.0005 ... 88.0757 91.0543 91.9719]
 [ 1.0084  2.0147 12.0005 ... 88.0757 91.0543 91.9719]
 [ 1.0084  2.0147 12.0005 ... 88.0757 91.0543 91.9719]
 ...
 [ 1.0084  2.0147 12.0005 ... 88.0757 91.0543 91.9719]
 [ 1.0084  2.0147 12.0005 ... 88.0757 91.0543 91.9719]
 [ 1.0084  2.0147 12.0005 ... 88.0757 91.0543 91.9719]]


In [123]:
# Calculate standard deviations and resulting probabilities for each mass according to its uncertainty pdf.
# We transform the x_data from 1 x n to n x 1, then broadcast it to n x 48 while subtracting precise_masses and dividing
# by the uncertainty to get the number of standard deviations each measured mass is from each of the 48 known species
# masses, then use norm.cdf to convert to probabilities.
prob_matrix = np.zeros((test_size,len(data)))
prob_matrix = (np.reshape(x_data, (-1,1)) - precise_masses) / (1000 * unc)  # TODO = 1e-1. This (overall) factor currently results in 8% accuracy @ 1e-5, 98% accuracy @ 1e-3, 97% accuracy @ 1e14, and 8% accuracy @ 1e17.
prob_matrix = (norm.cdf(-abs(prob_matrix)))

# Calculate relative probabilities by scaling row sum to 1
rel_prob_matrix = 1/np.reshape(np.sum(prob_matrix,1),(-1,1)) * prob_matrix
# Print out rows from the relative probability matrix to give us an idea of the output
print(np.round(rel_prob_matrix[0:3,:],4))

[[0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
  0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
  0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
  0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
  0.5372 0.4628 0.     0.     0.     0.     0.     0.     0.     0.
  0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
  0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
  0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
  0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
  0.     0.     0.     0.     0.     0.     0.    ]
 [0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
  0.     0.     0.     0.     0.     1.     0.     0.     0.     0.
  0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
  0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
  0.     0.     0.     0.     0.     0.     0.     0.     0.    

In [124]:
# Now let's compare our array with the real labels and determine the classification accuracy of the Gaussian Process
y_pred = np.argmax(rel_prob_matrix, 1)
species_pred = [data.at[y, 'Species'] for y in y_pred]
species_act = [data.at[y, 'Species'] for y in y_data]

print("\nPredicted: \n", species_pred)
print("\nActual: \n", species_act)

class_acc = (y_pred == y_data).mean()*100
print("\nClassification Accuracy: ", str(class_acc) + "%")


Predicted: 
 ['O2-', 'CNO-', 'Ca+', 'SiO2H-', 'SH-', 'C4H7+', 'C3H7+', 'C2-', 'NaSO4-', 'H2+', 'C7H7+', 'C3H7+', 'C3H6N+', 'BO2-', 'C2H3+', 'SO3-', 'C4H8N+', 'AlO2-', 'C16H31O2-', 'C18H35O2-', 'CH4N+', 'O-', 'O2H-', 'Li+', 'C18H33O2-', 'SO4-', 'Na+', 'CH4N+', 'OCH3+', 'Na2O+', '30Si+', 'AlO-', 'K+', 'C7H7+', 'Fe+', 'SO3-', '29Si+', 'C2H8N+', 'B+', 'C2H6N+', '6Li+', 'O-', 'C4H8N+', 'C2H3+', 'NO2-', 'H2+', 'C18H35O2-', 'AlO-', 'C2H-', '6Li+', 'CNO-', 'C2H-', 'NO2-', 'SiO2H-', 'C3H5+', 'Ca++', 'C4H8N+', 'Al+', 'Fe+', 'Na2NO2+', 'SH-', 'FeO2-', 'C4OH-', 'C2H-', 'C2H6N+', 'Cl-', 'O2-', 'NaSO4-', '25Mg+', 'CN-', 'K+', 'C4H9+', 'K+', 'C4H-', 'OH3+', 'C4H7+', '2H-', '30Si+', 'O2-', 'C4H5+', '26Mg+', 'K+', 'C4-', 'Si2+', 'C4H8N+', 'CaOH+', 'SiO2H-', 'SH-', 'B+', '41K+', 'Ca+', 'C4H8N+', 'SiC3H9+', 'Na2NO2+', 'CO2H-', 'NH4+', 'SiO2-', 'SH-', 'C5H12N+', 'C2H8N+']

Actual: 
 ['O2-', 'CNO-', 'Ca+', 'SiO2H-', 'SH-', 'C4H7+', 'C3H7+', 'C2-', 'NaSO4-', 'H2+', 'C7H7+', 'C3H7+', 'C3H6N+', 'BO2-', 'C2H3

In [125]:
# Show some incorrect classifications and what they should be
y_pred, y_data, species_pred, species_act = np.array(y_pred), np.array(y_data), np.array(species_pred), np.array(species_act)
prediction_mask = (y_pred != y_data)

print("\nIncorrect Predictions: \n", species_pred[prediction_mask])
print("\nCorrect Species: \n", species_act[prediction_mask])

print("\nIndices of Incorrect Predictions: \n", [i for i in range(len(prediction_mask)) if prediction_mask[i]])


Incorrect Predictions: 
 ['NO2-']

Correct Species: 
 ['Na2+']

Indices of incorrect classifications: 
 [44]
